version: '3.4'

services:
  db:
    image: bitnami/mysql:latest
    container_name: db
    user: root
    ports:
      - 3309:3306
    volumes:
      - ./db/data:/bitnami/mysql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'master'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'ZFhLrUg1QV9FzUy4x8RT'
  backend:
    build: ./web-backend
    container_name: web-backend
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload-dir ./ --host 0.0.0.0 --port 8000
    environment:
      DB_PORT: 3309
    links:
      - "db"
    depends_on:
      - db
  frontend:
    build: 
      context: ./web-frontend
      network: host
    container_name: web-frontend
    ports:
      - "7000:8080"

